### ISSUE TITLE
Left-shifting a negative value is undefined

### ISSUE THREAD

**Issue by gperciva** [cperciva/imds-filterd#3]
`imds-filterd/netconfig.c`, line 88:
```
                /* Which address type is this? */
                if ((i = ffs(rt->rtm_addrs & ((-1) << i))) == 0) {
                        warn0("Routing message contains wrong number of addresses!");
                        goto err0;
                }
```

I believe that `(-1) << i` is undefined in C99.  The spec says:

> C99 draft, 6.5.7 Bitwise shift operators
> ..
> 4. The result of E1 << E2 is E1 left-shifted E2 bit positions... If E1 has a signed
type and nonnegative value, and E1 × 2^{E2} is representable in the result type, then that is
the resulting value; otherwise, the behavior is undeﬁned.

One fix might be to change `(-1)` to `((size_t)-1)`, but I see that `struct rt_msghrd` contains `int rtmaddrs`.  So maybe the whole line should be
```
                if ((i = ffs(rt->rtm_addrs & (int)(((size_t)-1) << i))) == 0) {
```

But I've never worked with `man 4 route` before, nor do I have a good sense of what that code is doing, so I figured that I'd leave it to you.

**Comment by cperciva** [comment]
#4
